name: CI/CD Pipeline
#test
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest

  
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Validate DockerHub username
        run: |
          DOCKERHUB_USERNAME="soniagurram"
          if [ -z "$DOCKERHUB_USERNAME" ]; then
            echo "ERROR: DOCKERHUB_USERNAME is not set.";
            exit 1;
          fi
      - name: Build Docker image
        run: |
          DOCKERHUB_USERNAME="soniagurram"
          IMAGE_TAG="$DOCKERHUB_USERNAME/fastapi-app:latest"
          echo "Building image $IMAGE_TAG"
          docker build -t "$IMAGE_TAG" .
        
  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to DockerHub
        run: |
          DOCKERHUB_USERNAME="soniagurram"
          DOCKERHUB_PASSWORD="Sonia@77281"
          echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - name: Push Docker image
        run: |
          DOCKERHUB_USERNAME="soniagurram"
          IMAGE_TAG="$DOCKERHUB_USERNAME/fastapi-app:latest"
          echo "Pushing $IMAGE_TAG"
          docker push "docker.io/soniagurram/fastapi-app:latest"
   
  

  deploy:
    runs-on: ubuntu-latest
    needs: push
    steps:
      - name: Deploy to server
        run: echo "Deploy step here (e.g., SSH, Kubernetes, etc.)"
